words = ["Skydiving",
"Tango Dancing",
"Baking a Cake",
"Playing Tennis",
"Painting a Portrait",
"Writing a Love Letter",
"Doing Yoga",
"Building a Sandcastle",
"Playing the Guitar",
"Making a Collage",
"Going Ice Skating",
"Playing Charades",
"Flying a Kite",
"Putting Together a Puzzle",
"Playing Chess",
"Carving a Pumpkin",
"Playing the Piano",
"Gardening",
"Taking a Photo",
"Doing a Scientific Experiment",
"Knitting",
"Solving a Rubik's Cube",
"Bracelet",
"Doing Origami",
"Playing the Violin",
"Writing a Poem",
"Making a Smoothie",
"Making a Snowman",
"Playing Checkers",
"Birdhouse",
"Board Game",
"Doing a Crossword Puzzle",
"Necklace",
"Bingo",
"Sudoku",
"Playing the Drums",
"Playing Darts",
"Making a Pizza",
"Playing the Harmonica",
"Making a Birthday Card",
"Playing Table Tennis",
"Doing Karaoke",
"Making a Paper Airplane",
"Playing Horseshoes",
"Doing a Magic Trick",
"Playing the Ukulele",
"Making a Pottery Piece",
"Playing the Xylophone",
"Doing a Maze Puzzle",
"Candle",
"Playing the Trumpet",
"Doing a Memory Game",
"Playing the Flute",
"Playing the Saxophone",
"Playing Jenga",
"Making a Shadow Puppet",
"Playing the Clarinet"
"Riddle",
"Playing the Accordion",
"Playing the Banjo",
"Wind Chime",
"Dreamcatcher",
"Playing the Bagpipes",
"Flower",
"Making a Clay Sculpture",
"Playing the Organ",
"Making a Snow Globe"]